name: 回報問題
description: 回報某一則新聞的問題
title: "回報問題"
body:
  - type: input
    id: page
    attributes:
      label: 頁面網址
      description: 出問題的文章頁網址
    validations:
      required: false
  - type: textarea
    id: detail
    attributes:
      label: 問題說明
      description: 請寫下這則新聞哪裡不對。
    validations:
      required: true
